# Generated by Django 4.2.6 on 2023-11-25 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0004_profile_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='address',
            new_name='house_address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='full_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, default='Port Louis', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, default='Mauritius', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(default='Firstname', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='floorlevel',
            field=models.CharField(blank=True, default='Ground Floor', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default='Lastname', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default='Port Louis', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(default='Mauritius', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='floorlevel',
            field=models.CharField(default='Ground Floor', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='house_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phonenumber',
            field=models.CharField(default='+230 1234 5678', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, default='+230 1234 5678', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='Firstname', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='Lastname', max_length=100),
        ),
    ]
