# Generated by Django 4.2.6 on 2023-11-29 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0005_rename_address_profile_house_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(default='email@abc.com', max_length=254)),
                ('address', models.CharField(max_length=500)),
                ('floor_level', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=15)),
                ('furniture_type', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Contacts',
            },
        ),
    ]
