# Generated by Django 4.2.6 on 2023-11-29 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0006_contactus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name_plural': 'Contact Us'},
        ),
        migrations.AlterField(
            model_name='contactus',
            name='description',
            field=models.TextField(),
        ),
    ]
