# Generated by Django 4.2.6 on 2023-12-08 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0011_alter_profile_first_name_alter_profile_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='floorlevel',
        ),
    ]
