# Generated by Django 4.2.6 on 2023-12-11 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0012_remove_user_floorlevel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='phone_number',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='phonenumber',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='floorlevel',
        ),
        migrations.CreateModel(
            name='CustomFurnitureRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('delivery_address', models.TextField()),
                ('delivery_floor_level', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('uploads', models.ImageField(blank=True, null=True, upload_to='images')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
