# Generated by Django 4.2.6 on 2023-12-11 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0013_rename_phone_number_contactus_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfurniturerequest',
            name='uploads',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
