# Generated by Django 4.2.6 on 2024-02-18 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0016_sitevisitrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfurniturerequest',
            name='description',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(default=' ', max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='house_address',
            field=models.CharField(default=' ', max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='house_address',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
