# Generated by Django 4.2.6 on 2023-11-15 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_invoice_options_alter_quotation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipts',
            name='file',
            field=models.FileField(upload_to='receipts/'),
        ),
    ]
