# Generated by Django 4.2.6 on 2023-11-15 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_receipts_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='template_name',
            field=models.CharField(default='default_template', max_length=255, unique=True),
        ),
    ]
