# Generated by Django 4.2.6 on 2023-11-15 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_emailtemplate_template_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailtemplate',
            name='template_name',
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='email_template',
            field=models.CharField(default='default_template', max_length=255, unique=True),
        ),
    ]
