# Generated by Django 4.2.6 on 2023-11-29 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(default='email@abc.com', max_length=254),
        ),
    ]
