# Generated by Django 4.2.6 on 2023-11-30 03:16

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_invoice_payment_status_quotation_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abc12345678', length=10, max_length=20, prefix='inv_', unique=True),
        ),
        migrations.AlterField(
            model_name='receipts',
            name='receipt_number',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abc12345678', length=10, max_length=20, prefix='rct_', unique=True),
        ),
    ]
