# Generated by Django 4.2.6 on 2023-11-30 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_invoice_invoice_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='date',
            new_name='invoice_date',
        ),
        migrations.RenameField(
            model_name='quotation',
            old_name='date',
            new_name='quotation_date',
        ),
        migrations.RenameField(
            model_name='receipts',
            old_name='date',
            new_name='receipt_date',
        ),
    ]
