# Generated by Django 4.2.6 on 2023-12-02 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_wallettransaction_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
