# Generated by Django 4.2.6 on 2023-12-08 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_document_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='payment_status',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='quotation_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='receipts',
            name='receipt_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
