# Generated by Django 4.2.6 on 2023-12-08 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_remove_quotation_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
