# Generated by Django 4.2.6 on 2023-12-08 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_rename_document_id_document_document_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
