# Generated by Django 4.2.6 on 2023-12-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_delete_emailtemplate_remove_invoice_email_body_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='bank_details',
        ),
        migrations.AddField(
            model_name='invoice',
            name='account_name',
            field=models.TextField(default='Assemble Yourself Exclusive furnitures ltd'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='account_number',
            field=models.TextField(default='MCB Acct: 000449502171'),
        ),
    ]
