# Generated by Django 4.2.6 on 2024-01-08 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_remove_invoice_bank_details_invoice_account_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancestatement',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
