# Generated by Django 4.2.6 on 2024-01-15 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_balancestatement_balance_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorderrequest',
            name='invoice_no',
        ),
    ]
