# Generated by Django 4.2.6 on 2024-01-11 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_cartorderrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='item',
            field=models.CharField(default='Sofa', max_length=200),
        ),
    ]
