# Generated by Django 4.2.6 on 2024-01-11 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_cartorder_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorder',
            name='item',
        ),
    ]
