# Generated by Django 4.2.6 on 2024-01-18 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_refundpolicy'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarrantyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Warranty Policy',
            },
        ),
        migrations.AlterModelOptions(
            name='refundpolicy',
            options={'verbose_name_plural': 'Refund Policy'},
        ),
        migrations.AlterModelOptions(
            name='termsandconditions',
            options={'verbose_name_plural': 'Terms and Conditions'},
        ),
    ]
