# Generated by Django 4.2.6 on 2024-01-18 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_warrantypolicy_alter_refundpolicy_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnsAndCancellations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Returns and Cancellations',
            },
        ),
    ]
