# Generated by Django 4.2.6 on 2024-01-18 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_privacypolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='proof_of_invoice',
            field=models.FileField(blank=True, null=True, upload_to='proof_of_invoices/'),
        ),
    ]
