# Generated by Django 4.2.6 on 2024-01-25 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0049_projectimage_is_approved_walletusage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='walletusage',
            old_name='amount_used',
            new_name='amount_to_use',
        ),
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_comments', to='core.projectimage'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='quotation_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('user', 'image')},
        ),
    ]
