# Generated by Django 4.2.6 on 2024-01-25 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_rename_amount_used_walletusage_amount_to_use_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together=set(),
        ),
    ]
