# Generated by Django 4.2.6 on 2024-01-25 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_alter_comment_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='walletusage',
            old_name='amount_to_use',
            new_name='amount_used',
        ),
    ]
