# Generated by Django 4.2.6 on 2024-01-27 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_rename_amount_to_use_walletusage_amount_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='wallet_usage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
