# Generated by Django 4.2.6 on 2024-02-27 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0052_rename_amount_to_use_walletusage_amount_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='specifications',
        ),
        migrations.AddField(
            model_name='cartorderrequest',
            name='description',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='delivery_time_frame',
            field=models.TextField(blank=True, default='This is the delivery time frame', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='dimensions',
            field=models.TextField(blank=True, default='This is the product dimensions', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='materials',
            field=models.TextField(blank=True, default='This is the product materials', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='structure',
            field=models.TextField(blank=True, default='This is the product structure', null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=250.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='WalletFundsTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funds_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('proof_of_transfer', models.FileField(blank=True, null=True, upload_to='proof_of_payments/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OutstandingPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_details', models.TextField()),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('proof_of_payment', models.FileField(blank=True, null=True, upload_to='proof_of_payments/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
