# Generated by Django 4.2.6 on 2024-01-27 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_quotation_wallet_usage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='quotation_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
