# Generated by Django 4.2.6 on 2024-01-30 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0054_alter_quotation_quotation_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutstandingPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_details', models.TextField()),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('proof_of_payment', models.FileField(blank=True, null=True, upload_to='proof_of_payments/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
