# Generated by Django 4.2.6 on 2024-02-01 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_walletfundstransfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletfundstransfer',
            name='account_name',
            field=models.TextField(default='Assemble Yourself Exclusive furnitures ltd'),
        ),
        migrations.AddField(
            model_name='walletfundstransfer',
            name='account_number',
            field=models.TextField(default='MCB Acct: 000449502171'),
        ),
    ]
