# Generated by Django 4.2.6 on 2024-02-01 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_walletfundstransfer_account_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='walletfundstransfer',
            name='account_name',
        ),
        migrations.RemoveField(
            model_name='walletfundstransfer',
            name='account_number',
        ),
    ]
