# Generated by Django 4.2.6 on 2024-02-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_remove_walletfundstransfer_account_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorderrequest',
            name='description',
            field=models.CharField(default=None, max_length=5000),
        ),
    ]
