# Generated by Django 4.2.6 on 2024-02-01 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_cartorderrequest_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorderrequest',
            name='description',
            field=models.CharField(default=None, max_length=5000, null=True),
        ),
    ]
